### PR TITLE
Fixed CSRF vulnerability

### PR DESCRIPTION
**Pull request by anandtiwarics**

### CODE REVIEW

**Review by toufik-airane — COMMENTED** [review]
Dear @anandtiwarics,

**Regarding the size of the fix, would you mind to complete your contribution** with:
1. a description explaining what did you do.
2. the results of the unit test to ensure that the application is working fine.

Thank you for your contribution and keep going! 💪👏

**Comment by anandtiwarics** [comment]
To take advantage of CSRF protection, following these steps are implemented:

1. The CSRF middleware is activated by default in the MIDDLEWARE setting. Overrides that setting, `django.middleware.csrf.CsrfViewMiddleware` .

2. In any template that uses a POST form, used the  `{% csrf_token %} ` tag inside the <form> element if the form is for an internal

3. Added csrfmiddlewaretoken parameter for AJAX  

`csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()`

4. Converted all delete functionality from GET to POST request.

Please follow the official document for more details: [https://docs.djangoproject.com/en/3.0/ref/csrf/](https://docs.djangoproject.com/en/3.0/ref/csrf/)

**Comment by JamieSlome** [comment]
Thanks for providing the extra information - we will re-review next Friday! 🍰

**Review by toufik-airane — APPROVED** [review]

**Review by JamieSlome — APPROVED** [review]
LGTM 🍰

**Comment by huntr-helper** [comment]
Congratulations @anandtiwarics - your fix has been selected! :tada:<br><br>Thanks for being part of the community & helping secure the world\'s open source code.<br>If you have any questions, please respond in the comments section. Your bounty is on its way - keep hunting!

**Pull request merged**
